github.com:
    users:
        anondeveg:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: anondeveg
